modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="autosizedgui"
version="${version}"
displayName="AutoSizedGUI"
logoFile=""
credits=""
authors="Qikahome"
description='''
A library mod that automatically sizes and arranges GUI elements with adaptive layout, scrolling, and pagination support.
'''

[[dependencies.autosizedgui]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.autosizedgui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
