modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="autosizedgui"
version="1.0.0"
displayName="AutoSizedGUI"
logoFile=""
credits=""
authors="Qikahome"
description='''
A library mod that automatically sizes and arranges GUI elements with adaptive layout, scrolling, and pagination support.
'''

[[dependencies.autosizedgui]]
    modId="neoforge"
    mandatory=true
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.autosizedgui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
